Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FormatString:
  EnforcedStyle: percent

# we prefer compact if-else-end/case-when-end alignment
Lint/EndAlignment:
  AlignWith: variable

Style/CaseIndentation:
  IndentWhenRelativeTo: end

# Ruby 1.8 compatibility
Style/DotPosition:
  EnforcedStyle: trailing

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

# TODO: re-enable in the future
Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
