language: ruby
rvm:
    - 1.8.7
    - 1.9.3
    - 2.0.0
    - 2.1.9
    - 2.2.3
    - 2.3.1
    - 2.4.0
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.0.0 # rubocop no longer supports ruby < 2.1.0
cache: bundler
sudo: false
script:
  - bundle exec rake
  - bundle exec rubocop
