language: ruby
    - 2.1
    - 2.2
    - 2.3
    - 2.4
    - 2.5
# matrix:
#   allow_failures:
#     - rvm: 1.8.7
#     - rvm: 1.9.3
#     - rvm: 2.0.0 # rubocop no longer supports ruby < 2.1.0
cache: bundler
sudo: false
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
script:
  - bundle exec rake
  - bundle exec rubocop -D lib/
