name: CI
on:
  push:
    branches: master
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest"]
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3"]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Git repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@f26937343756480a8cb3ae1f623b9c8d89ed6984 # v1.196.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bundle exec rake

    - name: Run RuboCop
      run: bundle exec rubocop -D lib/

    - name: Upload coverage results
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
      with:
        files: coverage/coverage.xml
        disable_search: true
        token: ${{ secrets.CODECOV_TOKEN }}
