name: CI
on:
  push:
    branches: master
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest"]
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3"]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Git repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bundle exec rake

    - name: Run RuboCop
      run: bundle exec rubocop -D lib/

    - name: Upload coverage results
      uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a # v5.0.7
      with:
        files: coverage/coverage.xml
        disable_search: true
        token: ${{ secrets.CODECOV_TOKEN }}
